name: Try Things

on: [workflow_dispatch]

jobs:
  a:
    name: try contitional logic
    runs-on: ubuntu-latest
    
    steps: 
      - name: Single Condition
        if: ${{ 'a' == 'a' }}
        run: echo "works"

      - name: Multi Condition
        if: ${{ 'a' == 'a' && 'b' == 'b' }}
        run: echo "works"

      - name: MultiLine Condition
        if: | 
          ${{ 
              'true' == 'true' 
              && 'false' == 'false'
          }}
        run: echo "works"

      - name: Should skip MultiLine Condition
        if: ${{ 'true' == 'false' && 'false' == 'true' }}
        run: echo "shouldn't run this"

      - name: Should skip MultiLine Condition 2
        if: ${{
          'true' == 'false' &&
          'false' == 'true' 
          }}
        run: echo "shouldn't run this"

        
